modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="championoftheabyss"
version="1.0.0"
displayName="Champion of the Abyss"
description='''Un mod de acción cooperativo donde portales dimensionales traen caos al mundo.'''

[[dependencies.championoftheabyss]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
